ignored = ["github.com/codelingo/lingo/_examples"]

[[constraint]]
  name = "github.com/blang/semver"
  version = "~3.5.1"

[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "~1.20.0"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"
  version = "~1.1.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "~1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/rhysd/go-github-selfupdate"
